# Generated by Django 4.2.7 on 2023-12-27 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenOversizedTshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='pics')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('available_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=7), blank=True, null=True, size=None)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink')], max_length=7), blank=True, null=True, size=None)),
                ('material', models.CharField(max_length=255)),
                ('fit', models.CharField(choices=[('regular', 'Regular Fit'), ('slim', 'Slim Fit'), ('loose', 'Loose Fit')], max_length=10)),
                ('sleeve', models.CharField(choices=[('short', 'Short Sleeve'), ('long', 'Long Sleeve')], max_length=10)),
                ('wash', models.CharField(choices=[('machine', 'Machine Wash'), ('hand', 'Hand Wash')], max_length=10)),
                ('occasion', models.CharField(max_length=255)),
                ('neck_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenTshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='pics')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('available_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=7), blank=True, null=True, size=None)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink')], max_length=7), blank=True, null=True, size=None)),
                ('material', models.CharField(max_length=255)),
                ('fit', models.CharField(choices=[('regular', 'Regular Fit'), ('slim', 'Slim Fit'), ('loose', 'Loose Fit')], max_length=10)),
                ('sleeve', models.CharField(choices=[('short', 'Short Sleeve'), ('long', 'Long Sleeve')], max_length=10)),
                ('wash', models.CharField(choices=[('machine', 'Machine Wash'), ('hand', 'Hand Wash')], max_length=10)),
                ('occasion', models.CharField(max_length=255)),
                ('neck_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WomenOversizedTshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='pics')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('available_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=7), blank=True, null=True, size=None)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink')], max_length=7), blank=True, null=True, size=None)),
                ('material', models.CharField(max_length=255)),
                ('fit', models.CharField(choices=[('regular', 'Regular Fit'), ('slim', 'Slim Fit'), ('loose', 'Loose Fit')], max_length=10)),
                ('sleeve', models.CharField(choices=[('short', 'Short Sleeve'), ('long', 'Long Sleeve')], max_length=10)),
                ('wash', models.CharField(choices=[('machine', 'Machine Wash'), ('hand', 'Hand Wash')], max_length=10)),
                ('occasion', models.CharField(max_length=255)),
                ('neck_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WomenTshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='pics')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('available_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=7), blank=True, null=True, size=None)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink')], max_length=7), blank=True, null=True, size=None)),
                ('material', models.CharField(max_length=255)),
                ('fit', models.CharField(choices=[('regular', 'Regular Fit'), ('slim', 'Slim Fit'), ('loose', 'Loose Fit')], max_length=10)),
                ('sleeve', models.CharField(choices=[('short', 'Short Sleeve'), ('long', 'Long Sleeve')], max_length=10)),
                ('wash', models.CharField(choices=[('machine', 'Machine Wash'), ('hand', 'Hand Wash')], max_length=10)),
                ('occasion', models.CharField(max_length=255)),
                ('neck_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
