# Generated by Django 5.0 on 2023-12-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadStyle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menoversizedtshirt',
            name='image',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='mentshirt',
            name='image',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='womenoversizedtshirt',
            name='image',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='womentshirt',
            name='image',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
    ]
