# Generated by Django 4.2.7 on 2023-12-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadStyle', '0002_menoversizedtshirt_image_mentshirt_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menoversizedtshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='mentshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='womenoversizedtshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='womentshirt',
            name='color',
        ),
        migrations.AddField(
            model_name='menoversizedtshirt',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentshirt',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='womenoversizedtshirt',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='womentshirt',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menoversizedtshirt',
            name='available_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='available_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='womenoversizedtshirt',
            name='available_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='available_sizes',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=255, null=True),
        ),
    ]
