# Generated by Django 4.2.7 on 2023-12-26 15:12

import ThreadStyle.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThreadStyle', '0003_remove_menoversizedtshirt_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menoversizedtshirt',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='mentshirt',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='womenoversizedtshirt',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='womentshirt',
            name='colors',
        ),
        migrations.AddField(
            model_name='menoversizedtshirt',
            name='color',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('white', 'White'), ('yellow', 'Yellow')], max_length=None, null=True),
        ),
        migrations.AddField(
            model_name='mentshirt',
            name='color',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('white', 'White'), ('yellow', 'Yellow')], max_length=None, null=True),
        ),
        migrations.AddField(
            model_name='womenoversizedtshirt',
            name='color',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('white', 'White'), ('yellow', 'Yellow')], max_length=None, null=True),
        ),
        migrations.AddField(
            model_name='womentshirt',
            name='color',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('black', 'Black'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('white', 'White'), ('yellow', 'Yellow')], max_length=None, null=True),
        ),
        migrations.AlterField(
            model_name='menoversizedtshirt',
            name='available_sizes',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=None, null=True),
        ),
        migrations.AlterField(
            model_name='mentshirt',
            name='available_sizes',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=None, null=True),
        ),
        migrations.AlterField(
            model_name='womenoversizedtshirt',
            name='available_sizes',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=None, null=True),
        ),
        migrations.AlterField(
            model_name='womentshirt',
            name='available_sizes',
            field=ThreadStyle.models.MultiSelectField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=None, null=True),
        ),
    ]
